### PR TITLE
Update recipes to v5.0.0

### PR DESCRIPTION
**Pull request by joachimvh**
Also closes https://github.com/CommunitySolidServer/Recipes/issues/14 as an extra bonus

### CODE REVIEW

**Review by jeff-zucker — COMMENTED** [review]
I cloned 5.0, cut and pasted the new mashlib recipe config and tried to run the server.  Got : 
```
Could not build the config files from /home/jeff/Dropbox/Web/solid/css/mashlib-5-0-config.json
Cause: Error while parsing file "/home/jeff/Dropbox/Web/solid/css/mashlib-5-0-config.json": Unexpected STRING("css:config/util/logging/winston.json") in state COMMA
```

**Comment by joachimvh** [comment]
@jeff-zucker not sure what the cause would be. Is this a branch you already had on which you pulled the latest updates? Did you do an `npm ci` afterwards? Version 5 comes with a new version of components.js which might explain that error if it wasn't updated.

I just tried again with the following steps in my local repository on the main branch:

1. `npm ci`
2. Copy the mashlib config into `mashlib.json`
3. `npm start -- -c mashlib.json -f .data`

Which causes the server to start as expected. (And everything crashes if I try to browse to the server since I didn't install the required mashlib dependency in the steps above).

**Comment by jeff-zucker** [comment]
Yes, it must have been an artifact of a previous install.  I started in a fresh folder and the following led to a working 5.0.0 server with mashlib as the front-end : 
```
git clone https://github.com/CommunitySolidServer/CommunitySolidServer.git      
cd CommunitySolidServer                                                         
npm install --save mashlib                                                      
npm ci                                                                          
wget https://raw.githubusercontent.com/CommunitySolidServer/Recipes/v5.0.0/mashlib/config-mashlib.json                                                         
npm start -- -c config-mashlib.json -f .data          
```

**Comment by RubenVerborgh** [comment]
Great, thanks! Tested and confirmed working.

**Pull request merged**
